version: "3"
services:
  front-end:
    build: ./client
    container_name: getDexTokenPrices-frontend
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true 
    tty: true 
    depends_on:
      - back-end 
    networks:
      - getDexTokenPrices

  back-end:
    build: ./servers
    container_name: getDexTokenPrices-backend
    restart: always
    ports:
      - "5000: 5003"
    networks:
      - getDexTokenPrices

networks:
  getDexTokenPrices:
    driver: bridge