version: "3"
services:
  front-end:
    build: ./client
    container_name: getdextokenprices-frontend
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true 
    tty: true 
    depends_on:
      - back-end-bscv2
      - back-end-ethv2
      - back-end-ethv3
      - back-end-polygonv2
    networks:
      - getdextokenprice

  back-end-bscv2:
    build: ./servers/bscV2
    container_name: getdextokenprices-bscv2
    restart: always
    ports:
      - "5000:5000"
    networks:
      - getdextokenprices

  back-end-ethv2:
    build: ./servers/ethV2
    container_name: getdextokenprices-ethv2
    restart: always
    ports:
      - "5002:5002"
    networks:
      - getdextokenprices

  back-end-ethv3:
    build: ./servers/ethV3 
    container_name: getdextokenprices-ethv3 
    restart: always
    ports:
      - "5001:5001"
    networks:
      - getdextokenprices

  back-end-polygonv2:
    build: ./servers/polygonV2
    container_name: getdextokenprices-polygonv2
    restart: always 
    ports: 
      - "5003:5003"
    networks:
      - getdextokenprices

networks:
  getDexTokenPrices:
    driver: bridge